# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado documents/SEA_exp/lights/lights.srcs/sources_1/ip/AXIS_Data_RAM_1/AXIS_Data_RAM.xci
# IP: The module: 'AXIS_Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado documents/SEA_exp/lights/lights.srcs/sources_1/ip/AXIS_Data_RAM_1/AXIS_Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXIS_Data_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Vivado documents/SEA_exp/lights/lights.srcs/sources_1/ip/AXIS_Data_RAM_1/AXIS_Data_RAM.xci
# IP: The module: 'AXIS_Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado documents/SEA_exp/lights/lights.srcs/sources_1/ip/AXIS_Data_RAM_1/AXIS_Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXIS_Data_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
